BARCODE_CLEAR: c
BARCODE_HISTORY: '1'
BARCODE_HOTSPOT: h
BARCODE_RESET: r
BARCODE_SETTING: s
BARCODE_STATUS: '2'
CHECK_MATCH: true
GOOGLE_SHEET_API: https://script.google.com/macros/s/AKfycbytyWzAyEr5SGa6I8qqUgErLiFW6bMQcSloBNy-TgpboYmRuG5ToksfmQ7dsx4uHVqk4w/exec
GOOGLE_SHEET_URL: https://docs.google.com/spreadsheets/d/1qjwfbjsITCQXcdYV88soR3xk-NBUKpjGTuQ57IWG2Dc/edit?usp=sharing
HISTORY_DATA_PATH: ../data/data_history.csv
IMAGES_HISTORY_PATH: ../data/images/
LINE_TOKEN1: hSZKWJiXYZXrjUOAw1vPn7C6hjJBq8Ai21ImGZes1Pb
LINE_TOKEN2: ''
LINE_TOKEN3: ''
LOGO_PATH: static/crma_logo.png
PERSON_DATA_PATH: ../data/person_data.csv
UNIT_NAME: พัน.๒ รร.จปร.
WEAPON_DATA_PATH: ../data/weapon_data.csv
